In [ ]:
import numpy as np
from scipy.linalg import fractional_matrix_power


In [ ]:
Aaa=[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

In [ ]:
len(Aaa)

22

In [ ]:
Aa1=[0, 0.79,0.21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

In [ ]:
len(Aa1)

22

In [ ]:
Aa2=[0,0,0.91,0.01,0.02,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.06,0]

In [ ]:
len(Aa2)

22

In [ ]:
Aa3=[0,0,0.01,0.64,0.3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.06,0]

In [ ]:
len(Aa3)

22

In [ ]:
A1=[0,0,0,0.02,0.84,0.08,0.01,0.01,0,0,0,0,0,0,0,0,0,0,0,0,0.04,0]

In [ ]:
len(A1)

22

In [ ]:
A2=[0,0,0,0,0.17,0.74,0.03,0.01,0,0,0,0.01,0,0,0,0,0,0,0,0,0.03,0]

In [ ]:
len(A2)

22

In [ ]:
A3=[0,0,0,0,0,0.04,0.8,0.06,0.02,0,0,0,0,0,0,0,0,0,0,0,0.08,0]

In [ ]:
len(A3)

22

In [ ]:
Baa1=[0,0,0,0,0,0,0.05,0.85,6,0,0,0,0,0,0,0,0,0,0,0,0.04,0]

In [ ]:
len(Baa1)

22

In [ ]:
Baa2=[0,0,0,0,0,0,0,0.08,0.82,0.05,0,0,0,0,0,0,0,0,0,0,0.05,0]

In [ ]:
len(Baa2)

22

In [ ]:
Baa3=[0,0,0,0,0,0,0,0,0.09,0.8,0.04,0.01,0,0,0,0,0.01,0,0,0,0.06,0]

In [ ]:
len(Baa3)

22

In [ ]:
Ba1=[0,0,0,0,0,0,0,0,0.01,0.14,0.72,0.04,0.01,0,0,0,0,0,0,0,0.07,0]

In [ ]:
len(Ba1)

22

In [ ]:
Ba2=[0,0,0,0,0,0,0,0,0,0.03,0.11,0.72,0.03,0.02,0.02,0,0,0,0,0,0.07,0]

In [ ]:
len(Ba2)

22

In [ ]:
Ba3=[0,0,0,0,0,0,0,0,0,0.01,0.04,0.07,0.71,0.06,0.01,0.01,0.01,0,0,0,0.07,0]

In [ ]:
len(Ba3)

22

In [ ]:
len(Ba3)

22

In [ ]:
B1=[0,0,0,0,0,0,0,0,0,0,0,0.02,0.09,0.67,0.04,0.03,0,0,0.01,0,0.12,0]

In [ ]:
len(B1)

22

In [ ]:
B2=[0,0,0,0,0,0,0,0,0,0,0,0.01,0.02,0.07,0.59,0.08,0.03,0.03,0,0,0.15,0]

In [ ]:
len(B2)

22

In [ ]:
B3=[0,0,0,0,0,0,0,0,0,0,0,0,0.01,0.02,0.09,0.62,0.09,0.03,0,0,0.14,0.01]

In [ ]:
len(B3)

22

In [ ]:
Caa1=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.01,0.06,0.62,0.11,0.02,0.01,0.15,0.02]

In [ ]:
len(Caa1)

22

In [ ]:
Caa2=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.02,0.07,0.57,0.09,0.03,0.19,0.03]

In [ ]:
len(Caa2)

22

In [ ]:
Caa3=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.03,0.06,0.51,0.12,0.13,0.14]

In [ ]:
len(Caa3)

22

In [ ]:
CaC=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.03,0.02,0.03,0.41,0.16,0.35]

In [ ]:
len(CaC)

22

In [ ]:
WR=[0 for _ in range(22)]

In [ ]:
WR[-2]=1

In [ ]:
DEF=[0 for _ in range(22)]

In [ ]:
DEF[-1]=1

In [ ]:
M=[Aaa,Aa1,Aa2,Aa3,A1,A2,A3,Baa1,Baa2,Baa3,Ba1,Ba2,Ba3,B1,B2,B3,Caa1,Caa2,Caa3,CaC,WR,DEF]

In [ ]:
np_M=np.array(M)

In [ ]:
np_M2=fractional_matrix_power(np_M,2)

In [ ]:
np_M3=fractional_matrix_power(np_M,3)

In [ ]:
np_M4=fractional_matrix_power(np_M,4)

In [ ]:
np_M5=fractional_matrix_power(np_M,5)

In [ ]:
np_M[-7]

array([0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.01, 0.02, 0.09, 0.62, 0.09, 0.03, 0.  , 0.  , 0.14, 0.01])

In [ ]:
np_M2[-7]

array([0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e-04, 4.000e-04, 2.000e-03,
       1.690e-02, 3.270e-02, 1.107e-01, 3.983e-01, 1.165e-01, 4.830e-02,
       4.700e-03, 1.800e-03, 2.626e-01, 1.890e-02])

In [ ]:
np_M3[-7]

array([0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 1.30000e-05, 3.65000e-04,
       1.18800e-03, 4.40100e-03, 2.12030e-02, 3.86780e-02, 1.03842e-01,
       2.64908e-01, 1.15144e-01, 5.59340e-02, 9.45500e-03, 3.91600e-03,
       3.67799e-01, 2.79500e-02])

In [ ]:
np_M4[-7]

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0400000e-06,
       5.5390000e-05, 8.0303000e-04, 2.2021900e-03, 6.5160800e-03,
       2.3404980e-02, 3.9841560e-02, 8.8107110e-02, 1.8195001e-01,
       1.0287845e-01, 5.6256340e-02, 1.2663250e-02, 5.5696200e-03,
       4.5675654e-01, 3.7274280e-02])

In [ ]:
np_M5[-7]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 5.20000000e-08, 5.31520000e-06,
       1.45954400e-04, 1.38303230e-03, 3.27066600e-03, 8.10394640e-03,
       2.40024228e-02, 3.80349635e-02, 7.13455141e-02, 1.28584705e-01,
       8.75303632e-02, 5.23556443e-02, 1.41444013e-02, 6.51960890e-03,
       5.31184049e-01, 4.65612613e-02])

In [ ]:
np_M[-7][-1]+np_M[-7][-2]+(np_M2[-7][-1]+np_M2[-7][-2])+np_M3[-7][-1]+np_M3[-7][-2]+np_M4[-7][-1]+np_M4[-7][-2]+np_M5[-7][-1]+np_M5[-7][-2]

1.8990251305999999

In [ ]:
default1=np_M[-7][-1]

In [ ]:
print(default1)

0.01


In [ ]:
default2=(1-default1)*(np_M2[-7][-1])

In [ ]:
default2

0.018711

In [ ]:
default3=(1-default1-default2)*(np_M3[-7][-1])

In [ ]:
default3

0.02714752755

In [ ]:
default4=(1-default1-default2-default3)*(np_M4[-7][-1])

In [ ]:
default4

0.03519219360371358

In [ ]:
default5=(1-default1-default2-default3-default4)*(np_M5[-7][-1])

In [ ]:
default5

0.0423218248808085

In [ ]:
default1+default2+default3+default4+default5

0.1333725460345221